# Generated by Django 5.1.7 on 2025-03-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0002_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
