# Generated by Django 5.1.7 on 2025-03-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0004_remove_report_file_path_report_report_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
