# Generated by Django 5.1.7 on 2025-03-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0005_alter_report_report_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
