# Generated by Django 5.1.7 on 2025-04-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0006_alter_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
