# Generated by Django 5.1.7 on 2025-04-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0007_alter_report_report_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
