# Generated by Django 5.1.7 on 2025-04-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0008_alter_report_report_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
